#!/usr/bin/env python3
"""Create a SKILL.REF file that points to a canonical skill directory."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.reconcile import parse_frontmatter


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a SKILL.REF pointing to a canonical skill directory."
    )
    parser.add_argument(
        "canonical",
        type=Path,
        help="Path to the canonical skill directory (must contain SKILL.md).",
    )
    parser.add_argument(
        "target",
        type=Path,
        help="Directory where the SKILL.REF file will be created.",
    )
    parser.add_argument(
        "--relative",
        action="store_true",
        default=True,
        help="Use a relative path from target to canonical (default: true).",
    )
    parser.add_argument(
        "--absolute",
        action="store_true",
        help="Use an absolute path instead of relative.",
    )
    args = parser.parse_args()

    canonical = args.canonical.resolve()
    skill_md = canonical / "SKILL.md"
    if not skill_md.exists():
        raise SystemExit(f"No SKILL.md found in {canonical}")

    meta = parse_frontmatter(skill_md)
    target = args.target.resolve()
    target.mkdir(parents=True, exist_ok=True)

    ref_path = canonical if args.absolute else Path(os.path.relpath(canonical, target))
    ref_file = target / "SKILL.REF"
    ref_file.write_text(
        f"# Auto-generated by create_ref.py\n"
        f"# Canonical skill: {meta['name']}\n"
        f"ref: {ref_path}\n",
        encoding="utf-8",
    )
    print(f"Created reference: {ref_file} -> {ref_path}")


if __name__ == "__main__":
    import os
    main()
